version: '3'

services:
  db:
    image: postgres
    networks:
      - django-nginx

  backend:
    build: ./backend
    command: /start_dev.sh
    volumes:
      - .:/code
      - django-static:/backend/static
    networks:
      - django-nginx
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app/frontend:ro
    depends_on:
      - backend
    networks:
      - django-nginx

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
      - django-static:/usr/src/app/static
    networks:
      - django-nginx

volumes:
  django-static:

networks:
  django-nginx:
    driver: bridge
